// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAudioTools() {
  return window['go']['main']['App']['CheckAudioTools']();
}

export function ClearRecentEvents() {
  return window['go']['main']['App']['ClearRecentEvents']();
}

export function CreateRule(arg1) {
  return window['go']['main']['App']['CreateRule'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function DeleteSound(arg1) {
  return window['go']['main']['App']['DeleteSound'](arg1);
}

export function DeleteSounds(arg1) {
  return window['go']['main']['App']['DeleteSounds'](arg1);
}

export function EvaluateEvent(arg1) {
  return window['go']['main']['App']['EvaluateEvent'](arg1);
}

export function GetPlaybackStatus() {
  return window['go']['main']['App']['GetPlaybackStatus']();
}

export function GetSoundPreviewDataURL(arg1) {
  return window['go']['main']['App']['GetSoundPreviewDataURL'](arg1);
}

export function HandleTerminalEvent(arg1) {
  return window['go']['main']['App']['HandleTerminalEvent'](arg1);
}

export function ImportSoundPaths(arg1) {
  return window['go']['main']['App']['ImportSoundPaths'](arg1);
}

export function ImportSoundWithPicker() {
  return window['go']['main']['App']['ImportSoundWithPicker']();
}

export function ListRecentEvents() {
  return window['go']['main']['App']['ListRecentEvents']();
}

export function ListRules() {
  return window['go']['main']['App']['ListRules']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ProbeSoundDuration(arg1) {
  return window['go']['main']['App']['ProbeSoundDuration'](arg1);
}

export function ProcessSound(arg1) {
  return window['go']['main']['App']['ProcessSound'](arg1);
}

export function ProcessSounds(arg1) {
  return window['go']['main']['App']['ProcessSounds'](arg1);
}

export function RenameSound(arg1) {
  return window['go']['main']['App']['RenameSound'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectSoundFiles() {
  return window['go']['main']['App']['SelectSoundFiles']();
}

export function SimulateEvent(arg1) {
  return window['go']['main']['App']['SimulateEvent'](arg1);
}

export function StopPlayback() {
  return window['go']['main']['App']['StopPlayback']();
}

export function TestRuleSound(arg1) {
  return window['go']['main']['App']['TestRuleSound'](arg1);
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}

export function UpdateRule(arg1) {
  return window['go']['main']['App']['UpdateRule'](arg1);
}
