// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';
import {integrations} from '../models';

export function CheckAudioTools():Promise<main.AudioToolsStatus>;

export function ClearRecentEvents():Promise<Array<core.RecentEventRecord>>;

export function CreateRule(arg1:main.RuleRequest):Promise<core.ConfigSnapshot>;

export function DeleteRule(arg1:string):Promise<core.ConfigSnapshot>;

export function DeleteSound(arg1:string):Promise<core.ConfigSnapshot>;

export function DeleteSounds(arg1:Array<string>):Promise<core.ConfigSnapshot>;

export function EvaluateEvent(arg1:core.TerminalEvent):Promise<core.RuleMatchResult>;

export function GetPlaybackStatus():Promise<core.PlaybackStatus>;

export function GetSoundPreviewDataURL(arg1:string):Promise<string>;

export function HandleTerminalEvent(arg1:core.TerminalEvent):Promise<core.RuleMatchResult>;

export function ImportSoundPaths(arg1:Array<string>):Promise<core.ConfigSnapshot>;

export function ImportSoundWithPicker():Promise<core.ConfigSnapshot>;

export function InstallShellIntegration(arg1:string):Promise<integrations.DoctorResult>;

export function InstallZshIntegration():Promise<integrations.DoctorResult>;

export function ListHandledEventLog():Promise<Array<core.RecentEventRecord>>;

export function ListIntegrationStatuses():Promise<Array<integrations.IntegrationStatus>>;

export function ListRecentEvents():Promise<Array<core.RecentEventRecord>>;

export function ListRules():Promise<core.ConfigSnapshot>;

export function LoadConfig():Promise<core.ConfigSnapshot>;

export function ProbeSoundDuration(arg1:string):Promise<core.ConfigSnapshot>;

export function ProcessSound(arg1:string):Promise<core.ConfigSnapshot>;

export function ProcessSounds(arg1:Array<string>):Promise<core.ConfigSnapshot>;

export function RenameSound(arg1:main.RenameSoundRequest):Promise<core.ConfigSnapshot>;

export function RunIntegrationDoctor():Promise<integrations.DoctorResult>;

export function SaveConfig(arg1:core.AppConfig):Promise<core.ConfigSnapshot>;

export function SelectSoundFiles():Promise<Array<string>>;

export function SimulateEvent(arg1:core.TerminalEvent):Promise<core.RuleMatchResult>;

export function StopPlayback():Promise<core.PlaybackStatus>;

export function TestRuleSound(arg1:string):Promise<string>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<core.ConfigSnapshot>;

export function UninstallShellIntegration(arg1:string):Promise<integrations.DoctorResult>;

export function UninstallZshIntegration():Promise<integrations.DoctorResult>;

export function UpdateRule(arg1:main.RuleRequest):Promise<core.ConfigSnapshot>;
