// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSound(arg1) {
  return window['go']['main']['App']['DeleteSound'](arg1);
}

export function GetSoundPreviewDataURL(arg1) {
  return window['go']['main']['App']['GetSoundPreviewDataURL'](arg1);
}

export function ImportSoundPaths(arg1) {
  return window['go']['main']['App']['ImportSoundPaths'](arg1);
}

export function ImportSoundWithPicker() {
  return window['go']['main']['App']['ImportSoundWithPicker']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RenameSound(arg1) {
  return window['go']['main']['App']['RenameSound'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectSoundFiles() {
  return window['go']['main']['App']['SelectSoundFiles']();
}
